name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run train script
      # the following line successfully triggers the training and can actually save the model on Neptune
      # this means the communication from within the Github Actions container to outside is possible. 
        run: bash ../../ML-pipeline-End2End/ML-pipeline-End2End/train/train.sh
      - name: fetch model from Neptune
        run: python ../../ML-pipeline-End2End/ML-pipeline-End2End/artifacts/models/fetch_model.py
      - name: test downloaded model
        run: python ../../ML-pipeline-End2End/ML-pipeline-End2End/deploy/deploy.py
      # - name: deploy to Heroku
        
