name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run train script
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
        run: |
          git fetch --all --unshallow
          git log --oneline
          pwd 
          bash ../../ML-pipeline-End2End/ML-pipeline-End2End/train.sh
      - name: Push model to current Git repo
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git add -A
          git commit -m "added model files"
          git push
#       - name: deploy to Heroku
#         env:
#           NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
#           HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#           HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
#         run: |
#           git fetch --all --unshallow
#           git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
          
          
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: lingjun.l.zhou@gmail.com
